### PR TITLE
making program configurable

### PR DESCRIPTION
**Pull request by rzach**
I'd like the program list to be configurable. Right now the use of a `labeling` list is hardcoded. I could change it so that everything is done by commands which one could redefine. What do you think?

### CODE REVIEW

**Comment by jspitz** [comment]
I like the idea. In the examples you submitted, it seems it does not yet work as intended, right?

**Comment by rzach** [comment]
It should not break anything and produce the same output as before. I've only tried it out with the regular program and haven't tackled blocks yet.

**Comment by jspitz** [comment]
examples/German/lectureprogram.pdf in the changed files looks scrambled. Compare with the unchanged version.

**Comment by rzach** [comment]
Oh right sorry. I don't usually put PDFs into git so I forgot to compile everything before pushing.

I've now done this for the regular program list & exam list.  I don't really know how the beamer program list works and if its possible or worthwhile to also do this there. 

This will break, I think, if the metadata file contains `\SetBeamerFrameBreak`, since this will call `\@PauseBlock` and `\@ResumeBlock` and thisalso add things to `\programlist`. But I don't know why it should.

**Comment by jspitz** [comment]
Thanks, merged. I will need some time to test and maybe adjust this a bit.

**Comment by jspitz** [comment]
I have improved the macros a bit (used environments rather than Begin/End macros) and added more granular customization possibilities, at 57779583a1e59. Please check.

**Comment by jspitz** [comment]
@rzach FYI as of 15b57e664ed7 also beamer program can be customized.

**Comment by rzach** [comment]
Super, danke!

**Pull request merged**
